version: "3.7"
services:
  app:
    build:
      context: ../.
      dockerfile: ./Dockerfile
    network_mode: "host"
    env_file: .env
    healthcheck:
      test: curl -f localhost:8080/health
      interval: 10s
      timeout: 3s
      retries: 3